/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Christoph
 */
public class MainView extends javax.swing.JFrame 
{
  /**
   * @return the btnDeleteLine
   */
  public javax.swing.JButton getBtnDeleteLine()
  {
    return btnDeleteLine;
  }

  /**
   * @return the mniDelteLine
   */
  public javax.swing.JMenuItem getMniDeleteLine()
  {
    return mniDelteLine;
  }

  /**
   * @return the pumDeleteLine
   */
  public javax.swing.JMenuItem getPumDeleteLine()
  {
    return pumDeleteLine;
  }
  /**
   * @return the btnSaveAs
   */
  public javax.swing.JButton getBtnSaveAs()
  {
    return btnSaveAs;
  }
  /**
   * @return the pumSave
   */
  public javax.swing.JMenuItem getPumSave()
  {
    return pumSave;
  }
  /**
   * @return the pumOpen
   */
  public javax.swing.JMenuItem getPumOpen()
  {
    return pumOpen;
  }

  /**
   * @return the pumPopUp
   */
  public javax.swing.JPopupMenu getPumPopUp()
  {
    return pumPopUp;
  }

  /**
   * Creates new form MainView
   */
  public MainView()
  {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    fcFileChooser = new javax.swing.JFileChooser();
    pumPopUp = new javax.swing.JPopupMenu();
    pumOpen = new javax.swing.JMenuItem();
    pumSave = new javax.swing.JMenuItem();
    pumSaveAs = new javax.swing.JMenuItem();
    pumUndo = new javax.swing.JMenuItem();
    pumDeleteLine = new javax.swing.JMenuItem();
    tbOpenSave = new javax.swing.JToolBar();
    btnOpen = new javax.swing.JButton();
    btnSave = new javax.swing.JButton();
    btnSaveAs = new javax.swing.JButton();
    btnUndo = new javax.swing.JButton();
    btnDeleteLine = new javax.swing.JButton();
    lblFile = new javax.swing.JLabel();
    taEditor = new View.Edit();
    mnBar = new javax.swing.JMenuBar();
    mnFile = new javax.swing.JMenu();
    mniOpen = new javax.swing.JMenuItem();
    mniSave = new javax.swing.JMenuItem();
    mniSaveAs = new javax.swing.JMenuItem();
    mnEdit = new javax.swing.JMenu();
    mniUndo = new javax.swing.JMenuItem();
    mniDelteLine = new javax.swing.JMenuItem();

    fcFileChooser.setCurrentDirectory(new java.io.File("C:\\Users\\Christoph\\Desktop"));

    pumPopUp.setAutoscrolls(true);
    pumPopUp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    pumPopUp.setName(""); // NOI18N

    pumOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icons/Open24.gif"))); // NOI18N
    pumOpen.setMnemonic('o');
    pumOpen.setText("Open");
    pumOpen.setToolTipText("Open File");
    pumPopUp.add(pumOpen);

    pumSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icons/Save24.gif"))); // NOI18N
    pumSave.setMnemonic('s');
    pumSave.setText("Save");
    pumSave.setToolTipText("Save File");
    pumSave.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        pumSaveActionPerformed(evt);
      }
    });
    pumPopUp.add(pumSave);

    pumSaveAs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icons/SaveAs24.gif"))); // NOI18N
    pumSaveAs.setMnemonic('a');
    pumSaveAs.setText("Save As");
    pumSaveAs.setToolTipText("Save File As");
    pumSaveAs.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        pumSaveAsActionPerformed(evt);
      }
    });
    pumPopUp.add(pumSaveAs);

    pumUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icons/Undo24.gif"))); // NOI18N
    pumUndo.setMnemonic('u');
    pumUndo.setText("Undo");
    pumUndo.setToolTipText("Undo");
    pumUndo.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        pumUndoActionPerformed(evt);
      }
    });
    pumPopUp.add(pumUndo);

    pumDeleteLine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icons/Delete24.gif"))); // NOI18N
    pumDeleteLine.setMnemonic('d');
    pumDeleteLine.setText("Delete Line");
    pumDeleteLine.setToolTipText("Delete Line");
    pumDeleteLine.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        pumDeleteLineActionPerformed(evt);
      }
    });
    pumPopUp.add(pumDeleteLine);

    pumPopUp.setVisible(true);

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    tbOpenSave.setRollover(true);

    btnOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icons/Open24.gif"))); // NOI18N
    btnOpen.setToolTipText("Open File");
    btnOpen.setFocusable(false);
    btnOpen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnOpen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    tbOpenSave.add(btnOpen);

    btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icons/Save24.gif"))); // NOI18N
    btnSave.setToolTipText("Save File");
    btnSave.setFocusable(false);
    btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    tbOpenSave.add(btnSave);

    btnSaveAs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icons/SaveAs24.gif"))); // NOI18N
    btnSaveAs.setToolTipText("Save File As");
    btnSaveAs.setFocusable(false);
    btnSaveAs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnSaveAs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    tbOpenSave.add(btnSaveAs);

    btnUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icons/Undo24.gif"))); // NOI18N
    btnUndo.setToolTipText("Undo");
    btnUndo.setFocusable(false);
    btnUndo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnUndo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    btnUndo.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        btnUndoActionPerformed(evt);
      }
    });
    tbOpenSave.add(btnUndo);

    btnDeleteLine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icons/Delete24.gif"))); // NOI18N
    btnDeleteLine.setMnemonic('d');
    btnDeleteLine.setToolTipText("Delete Line");
    btnDeleteLine.setFocusable(false);
    btnDeleteLine.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnDeleteLine.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    tbOpenSave.add(btnDeleteLine);

    getContentPane().add(tbOpenSave, java.awt.BorderLayout.PAGE_START);

    lblFile.setText("File:");
    getContentPane().add(lblFile, java.awt.BorderLayout.PAGE_END);

    taEditor.setToolTipText("");
    taEditor.setComponentPopupMenu(pumPopUp);
    getContentPane().add(taEditor, java.awt.BorderLayout.CENTER);

    mnFile.setMnemonic('s');
    mnFile.setText("File");

    mniOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
    mniOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icons/Open24.gif"))); // NOI18N
    mniOpen.setMnemonic('o');
    mniOpen.setText("Open");
    mnFile.add(mniOpen);

    mniSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
    mniSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icons/Save24.gif"))); // NOI18N
    mniSave.setMnemonic('s');
    mniSave.setText("Save");
    mniSave.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        mniSaveActionPerformed(evt);
      }
    });
    mnFile.add(mniSave);

    mniSaveAs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
    mniSaveAs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icons/SaveAs24.gif"))); // NOI18N
    mniSaveAs.setMnemonic('a');
    mniSaveAs.setText("Save As");
    mniSaveAs.setToolTipText("Save File As");
    mniSaveAs.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        mniSaveAsActionPerformed(evt);
      }
    });
    mnFile.add(mniSaveAs);

    mnBar.add(mnFile);

    mnEdit.setMnemonic('E');
    mnEdit.setText("Edit");

    mniUndo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
    mniUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icons/Undo24.gif"))); // NOI18N
    mniUndo.setMnemonic('u');
    mniUndo.setText("Undo");
    mniUndo.setToolTipText("Undo");
    mnEdit.add(mniUndo);

    mniDelteLine.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
    mniDelteLine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icons/Delete24.gif"))); // NOI18N
    mniDelteLine.setMnemonic('d');
    mniDelteLine.setText("Delete Line");
    mniDelteLine.setToolTipText("Delete Line");
    mnEdit.add(mniDelteLine);

    mnBar.add(mnEdit);

    setJMenuBar(mnBar);

    setSize(new java.awt.Dimension(418, 347));
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void mniSaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mniSaveActionPerformed
  {//GEN-HEADEREND:event_mniSaveActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_mniSaveActionPerformed

  private void pumSaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_pumSaveActionPerformed
  {//GEN-HEADEREND:event_pumSaveActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_pumSaveActionPerformed

  private void pumSaveAsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_pumSaveAsActionPerformed
  {//GEN-HEADEREND:event_pumSaveAsActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_pumSaveAsActionPerformed

  private void mniSaveAsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mniSaveAsActionPerformed
  {//GEN-HEADEREND:event_mniSaveAsActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_mniSaveAsActionPerformed

  private void btnUndoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnUndoActionPerformed
  {//GEN-HEADEREND:event_btnUndoActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnUndoActionPerformed

  private void pumUndoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_pumUndoActionPerformed
  {//GEN-HEADEREND:event_pumUndoActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_pumUndoActionPerformed

  private void pumDeleteLineActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_pumDeleteLineActionPerformed
  {//GEN-HEADEREND:event_pumDeleteLineActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_pumDeleteLineActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new MainView().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnDeleteLine;
  private javax.swing.JButton btnOpen;
  private javax.swing.JButton btnSave;
  private javax.swing.JButton btnSaveAs;
  private javax.swing.JButton btnUndo;
  private javax.swing.JFileChooser fcFileChooser;
  public javax.swing.JLabel lblFile;
  private javax.swing.JMenuBar mnBar;
  private javax.swing.JMenu mnEdit;
  private javax.swing.JMenu mnFile;
  private javax.swing.JMenuItem mniDelteLine;
  private javax.swing.JMenuItem mniOpen;
  private javax.swing.JMenuItem mniSave;
  private javax.swing.JMenuItem mniSaveAs;
  private javax.swing.JMenuItem mniUndo;
  private javax.swing.JMenuItem pumDeleteLine;
  private javax.swing.JMenuItem pumOpen;
  private javax.swing.JPopupMenu pumPopUp;
  private javax.swing.JMenuItem pumSave;
  private javax.swing.JMenuItem pumSaveAs;
  private javax.swing.JMenuItem pumUndo;
  private View.Edit taEditor;
  private javax.swing.JToolBar tbOpenSave;
  // End of variables declaration//GEN-END:variables

  /**
   * @return the btnOpen
   */
  public javax.swing.JButton getBtnOpen()
  {
    return btnOpen;
  }

  /**
   * @return the btnSave
   */
  public javax.swing.JButton getBtnSave()
  {
    return btnSave;
  }

  /**
   * @return the mnEdit
   */
  public javax.swing.JMenu getMnEdit()
  {
    return mnEdit;
  }

  /**
   * @return the mnFile
   */
  public javax.swing.JMenu getMnFile()
  {
    return mnFile;
  }

  /**
   * @return the mniOpen
   */
  public javax.swing.JMenuItem getMniOpen()
  {
    return mniOpen;
  }

  /**
   * @return the mniSave
   */
  public javax.swing.JMenuItem getMniSave()
  {
    return mniSave;
  }

  /**
   * @return the fcFileChooser
   */
  public javax.swing.JFileChooser getFcFileChooser()
  {
    return fcFileChooser;
  }

  /**
   * @return the lblFile
   */
  public javax.swing.JLabel getLblFile()
  {
    return lblFile;
  }

  /**
   * @return the taEditor
   */
  public View.Edit getTaEditor()
  {
    return taEditor;
  }

  /**
   * @return the mniSaveAs
   */
  public javax.swing.JMenuItem getMniSaveAs()
  {
    return mniSaveAs;
  }

  /**
   * @return the pumSaveAs
   */
  public javax.swing.JMenuItem getPumSaveAs()
  {
    return pumSaveAs;
  }

  /**
   * @return the btnUndo
   */
  public javax.swing.JButton getBtnUndo()
  {
    return btnUndo;
  }

  /**
   * @return the mniUndo
   */
  public javax.swing.JMenuItem getMniUndo()
  {
    return mniUndo;
  }

  /**
   * @return the pumUndo
   */
  public javax.swing.JMenuItem getPumUndo()
  {
    return pumUndo;
  }

}
